version: '3.8'

services:
  # Rails application service
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    depends_on:
      - db
      - redis

  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sample_app_development
      POSTGRES_USER: sample_app
      POSTGRES_PASSWORD: <%= ENV['SAMPLE_APP_DATABASE_PASSWORD'] %>
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Redis service (optional)
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
